export const Questions = [
  {
    prompt: "What is my name?",
    optionA: "John",
    optionB: "Jake",
    optionC: "Josh",
    optionD: "Naveen kumar v",
    asnwer: "optionD",
  },
  {
    prompt: "Which of this is not a programming language?",
    optionA: "Python",
    optionB: "JavaScript",
    optionC: "MC-03",
    optionD: "Java",
    asnwer: "optionC",
  },
  {
    prompt: "Which of this is not a javascript framework?",
    optionA: "React",
    optionB: "Angular",
    optionC: "Vue",
    optionD: "Java",
    asnwer: "optionD",
  },
  {
    prompt: "Wat is the square root of 2?",
    optionA: "4",
    optionB: "6",
    optionC: "8",
    optionD: "10",
    asnwer: "optionA",
  },
  {
    prompt: "How many wonders in the world?",
    optionA: "7",
    optionB: "10",
    optionC: "8",
    optionD: "9",
    asnwer: "optionA",
  },
  {
    prompt: "Tajmahal located in which place?",
    optionA: "Agra",
    optionB: "Mumbai",
    optionC: "Kolkata",
    optionD: "Pujab",
    asnwer: "optionA",
  },
];
